language: c

before_install:
 - wget http://www.mpich.org/static/downloads/3.2/mpich-3.2.tar.gz
 - tar xfz mpich-3.2.tar.gz
 - cd mpich-3.2
 - ./configure --prefix=`pwd`/../mpich  --enable-static=false --enable-alloca=true --disable-long-double --enable-threads=single --enable-fortran=no --enable-fast=all --enable-g=none --enable-timing=none
 - make -j4
 - make install
script:
        make
